version: "3"
services:
  nest-basic-layout-dev:
    container_name: nest-basic-layout-development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - nms
    links:
      - db
      - nms
    networks:
      - nest-basic-layout-network
  db:
    image: postgres:12.2
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - nest-basic-layout-network

networks:
  nest-basic-layout-network:
    driver: bridge